### ISSUE TITLE
It doesn't work in my Vscode 

### ISSUE THREAD

**Issue by AndyHuyidi** [mjbvz/vscode-markdown-image-size#3]
Hi, it doesn't work for my Markdown. What's the problem ?
![image](https://user-images.githubusercontent.com/48292864/67257339-1a141c80-f4be-11e9-8a79-caa5e47565b8.png)
![image](https://user-images.githubusercontent.com/48292864/67257345-1e403a00-f4be-11e9-81d4-76eccc015f75.png)

**Comment by mjbvz** [comment]
Closing as this issue is out of date. If you are still seeing this issue, please share some example markdown text that demonstrates the issue
